[bar]
scale = 1.0
padding-ends = 0.0
module-gap = 1.2000000476837158
border-width = 0
border-color = "bg-base"
button-icon-size = 0.75
button-label-size = 0.75
button-label-weight = "medium"
button-gap = 0.25
button-border-width = 0

[[bar.layout]]
monitor = "*"
show = true
left = ["media"]
right = [
    "brightness",
    "volume",
    "bluetooth",
    "network",
    "battery",
]

[[bar.layout.center]]
module = "clock"
class = "clock-hero"

[styling]
scale = 1.0

[modules.hyprland-workspaces]
monitor-specific = false
icon-size = 0.3499999940395355
label-size = 0.8500000238418579

[wallpaper]
engine-enabled = true
cycling-directory = "/home/pineapple/Pictures/Wallpapers/alena-aenami-eclipse-1k.jpg"
