alias vim='~/Applications/nvim.appimage'
alias commands='cat ~/.config/.bash_aliases'
alias updatedb='sudo updatedb'
alias fastboot='sudo ~/Downloads/platform-tools/fastboot'
alias adb='~/Downloads/platform-tools/adb'
alias bat='batcat'
