[window]
opacity=0.85
padding = { x = 5, y = 5 }
title = "Terminal"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12

[colors.primary]
foreground = "#d0cfcc"
background = "#171421"

[colors.normal]
black = "#171421"
red = "#c01c28"
green = "#26A269"
yellow = "#e9ad0c"
blue = "#12488b"
magenta = "#f66151"
cyan = "#33c7de"
white = "#d0cfcc" 
